version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-wfh1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: new_employee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5407:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: backend-wfh1
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=new_employee_db
      - DB_PASSWORD=admin234
      - DB_PORT=5432
      - FRONTEND_URL=http://13.201.63.96:8012
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./Frontend
    container_name: frontend-wfh1
    ports:
      - "8012:80"

  hr_page:
    build: ./HR_page
    container_name: hrpage-wfh1
    ports:
      - "8013:80"

volumes:
  postgres_data:

